# Generated by Django 5.0.1 on 2024-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_groceryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/grocery_image/'),
        ),
    ]
